[platformio]
default_envs = esp32dev
extra_configs = platformio.local.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = espota

[env:esp32usb]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 460800
